### ISSUE TITLE
Shopify Launch: Checklist

### ISSUE THREAD

**Issue by sepowitz** [sanctuarycomputer/nunu#132]
- [x] Remove Password Protection
- [x] Add chosen sales channel
- [x] Add custom domain
- [x] Review Checkout and Payment Gateway
- [x] Review email notification settings
- [x] Adjust tax and shipping settings
- [x] Setup billing info
- [x] Ensure non-physical products are configured as such

For reference: https://www.shopify.com/blog/shopify-store-launch-checklist#channels
